# Generated by Django 3.0.2 on 2020-02-14 08:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Feedback', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='E_Date',
            field=models.DateField(default=datetime.date(2020, 2, 16)),
        ),
        migrations.AddField(
            model_name='feedback',
            name='Expiry',
            field=models.DurationField(default=None),
        ),
        migrations.AddField(
            model_name='feedback',
            name='Feedbacks',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='Date',
            field=models.CharField(default=datetime.date(2020, 2, 14), max_length=20),
        ),
    ]
