# Generated by Django 3.0.2 on 2020-02-14 09:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Feedback', '0003_auto_20200214_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='Expiry',
            field=models.DurationField(default=datetime.timedelta(days=20, seconds=36000), null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='Uid',
            field=models.CharField(default='0', max_length=20),
        ),
    ]
