# Generated by Django 3.0.2 on 2020-02-14 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Feedback', '0004_auto_20200214_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='Expiry',
            field=models.DurationField(),
        ),
    ]
