# Generated by Django 3.0.2 on 2020-02-14 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Feedback', '0005_auto_20200214_1433'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.DurationField()),
            ],
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='Expiry',
        ),
    ]
