# Generated by Django 3.0.2 on 2020-02-14 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Feedback', '0008_remove_feedback_e_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyModel',
        ),
        migrations.AddField(
            model_name='feedback',
            name='Expiry',
            field=models.CharField(default='0', max_length=20),
        ),
        migrations.AddField(
            model_name='feedback',
            name='Feedbacks',
            field=models.IntegerField(default=0),
        ),
    ]
