# Generated by Django 3.0.2 on 2020-02-14 09:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Feedback', '0009_auto_20200214_1446'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Uid', models.CharField(default='0', max_length=20)),
                ('Date', models.CharField(default=datetime.date(2020, 2, 14), max_length=20)),
                ('Feedbacks', models.IntegerField(default=0)),
                ('Expiry', models.CharField(default='0', max_length=20)),
            ],
            options={
                'verbose_name': 'Feed',
                'verbose_name_plural': 'Feeds',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
