# Generated by Django 2.2.5 on 2020-02-14 18:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Feedback', '0010_auto_20200214_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='Date',
            field=models.CharField(default=datetime.date(2020, 2, 15), max_length=20),
        ),
    ]
