# Generated by Django 2.2.5 on 2019-12-23 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pages', '0012_auto_20191223_2020'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dept',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='dept',
            name='Hospital_id',
        ),
        migrations.DeleteModel(
            name='Hospital',
        ),
    ]
