# Generated by Django 2.2.5 on 2019-12-23 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Pages', '0013_auto_20191223_2023'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('Hospital_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('Hospital_name', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='dept',
            name='Hospital_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Pages.Hospital'),
        ),
        migrations.AlterUniqueTogether(
            name='dept',
            unique_together={('Uid', 'Hospital_id')},
        ),
    ]
