# Generated by Django 2.2.6 on 2019-12-23 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Pages', '0014_auto_20191223_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dept',
            name='Hospital_id',
            field=models.ForeignKey(default='null', on_delete=django.db.models.deletion.CASCADE, to='Pages.Hospital'),
        ),
    ]
