# Generated by Django 3.0 on 2019-12-24 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pages', '0015_auto_20191223_2208'),
    ]

    operations = [
        migrations.AddField(
            model_name='dept',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='dept',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='dept',
            name='Uid',
        ),
    ]
