# Generated by Django 3.0 on 2019-12-24 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pages', '0016_auto_20191224_1935'),
    ]

    operations = [
        migrations.AddField(
            model_name='dept',
            name='Uid',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
