# Generated by Django 3.0 on 2019-12-24 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pages', '0017_dept_uid'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dept',
            unique_together={('Uid', 'Hospital_id')},
        ),
    ]
