# Generated by Django 2.2.6 on 2020-01-06 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pages', '0018_auto_20191224_1938'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='Image',
            field=models.ImageField(default='', upload_to='Hospital_images/'),
        ),
    ]
