# Generated by Django 2.2.8 on 2020-02-12 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pages', '0020_dept_route_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='dept',
            name='Desc',
            field=models.TextField(default='Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatem dignissimos aut voluptatum vero. Blanditiis officia natus odio placeat minima vero quod, magnam laborum, deleniti corporis, excepturi porro quo sunt perspiciatis ea ipsa fugit nihil atque! Nobis dolore explicabo officiis voluptatibus dignissimos odit perferendis, quam iste veniam. Aperiam nihil tenetur voluptatibus! Minus rem deserunt quas illo ipsum explicabo, officia illum sed accusantium, deleniti eveniet non. Labore quaerat tempora officiis ab fuga itaque dolor, sint fugit? Qui, obcaecati! Error in eius numquam officia inventore, assumenda consectetur fugit unde quasi quidem quos ea voluptas incidunt explicabo non reiciendis excepturi quo alias asperiores autem!'),
        ),
    ]
