# Generated by Django 2.2.8 on 2020-02-13 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Pages', '0021_dept_desc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dept',
            name='id',
        ),
        migrations.RemoveField(
            model_name='dept',
            name='route_image',
        ),
        migrations.AlterField(
            model_name='dept',
            name='Desc',
            field=models.TextField(default='Lorem ipsum dolor quo alias asperiores autem!'),
        ),
        migrations.AlterField(
            model_name='dept',
            name='Uid',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.CreateModel(
            name='doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_name', models.TextField()),
                ('doctor_time', models.IntegerField()),
                ('Uid', models.ForeignKey(default='null', on_delete=django.db.models.deletion.CASCADE, to='Pages.Dept')),
            ],
            options={
                'unique_together': {('Uid', 'doctor_name')},
            },
        ),
    ]
