# Generated by Django 2.2.8 on 2020-02-15 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pages', '0022_auto_20200213_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dept',
            name='image',
            field=models.ImageField(default='department_images/dept.jpg', upload_to='department_images/'),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='Image',
            field=models.ImageField(default='Hospital_images/ambani.jpg', upload_to='Hospital_images/'),
        ),
    ]
